finish automation.yml

diff --git a/.github/workflows/automation.yml b/.github/workflows/automation.yml
--- a/.github/workflows/automation.yml
+++ b/.github/workflows/automation.yml
@@ -16,7 +16,9 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       app_tag: ${{ steps.set-tags.outputs.app_tag }}
+      app_tag_latest: ${{ steps.set-tags.outputs.app_tag_latest }}
       nginx_tag: ${{ steps.set-tags.outputs.nginx_tag }}
+      nginx_tag_latest: ${{ steps.set-tags.outputs.nginx_tag_latest }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -85,7 +87,7 @@ jobs:
           envs: APP_TAG,NGINX_TAG
           script: |
             # log in to Docker Hub
-            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}"  --password-stdin
+            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}"  --password-stdin || {echo "Docker login failed"; exit 1;}
 
             echo "Logged in to Docker Hub"
 
@@ -146,7 +148,7 @@ jobs:
                 healthcheck:
                   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
                   interval: 30s
-                  timeout: 10s
+                  timeout: 15s
                   retries: 3
               db:
                 image: postgis/postgis:16-3.4
@@ -171,12 +173,12 @@ jobs:
                   - static_volume:/home/app/web/static
                   - media_volume:/home/app/web/media
                 depends_on:
-                    web
-                      condition: service_healthy
+                  web
+                    condition: service_healthy
                 networks:
                   - app-network
                 healthcheck:
-                  test: ["CMD", "curl", "-f", "http://localhost"]
+                  test: ["CMD", "curl", "-f", "http://localhost/health"]
                   interval: 30s
                   timeout: 10s
                   retries: 3
@@ -192,9 +194,9 @@ jobs:
             echo "docker-compose.yml created..."
             
             # Deploy with Docker Compose
-            docker-compose --project-name meq-data-app down --remove-orphans
-            docker-compose --project-name meq-data-app pull
-            docker-compose --project-name meq-data-app up -d --force-recreate
+            docker-compose --project-name meq-data-app down --remove-orphans || { echo "Docker Compose down failed"; exit 1; }
+            docker-compose --project-name meq-data-app pull || { echo "Docker Compose pull failed"; exit 1;}
+            docker-compose --project-name meq-data-app up -d --force-recreate || { echo "Docker Compose up failed"; exit 1; }
 
             # clean up unused images
             docker image prune -f
